repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: detect-aws-credentials
    args: [ "--allow-missing-credentials" ]
  - id: detect-private-key
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

# Strong secret scanner
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.4
  hooks:
  - id: gitleaks
    args: [ "protect", "--staged", "--no-banner" ]

# Optional: baseline-driven detector (lets you accept existing noise)
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    args: [ "--baseline", ".secrets.baseline" ]
